language: ruby
cache: bundler
bundler_args: --deployment
rvm:
  - 2.0.0
  - 1.9.3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec/
before_script:
   - /bin/cp $TRAVIS_BUILD_DIR/config/database.yml.sample $TRAVIS_BUILD_DIR/config/database.yml
   - psql -c 'create database movies_test;' -U postgres
   - psql -d template1 -c 'create extension hstore;' -U postgres
   - psql movies_test -c 'CREATE EXTENSION IF NOT EXISTS hstore' -U postgres
env:
  RAILS_ENV=test
notifications:
  webhooks:
    - http://107.170.50.35:5000/hubot/travis?room=%23ace.dimasuhid%2F%24eaguinaldy%3Bd4cc8989544f5a26

